DROP TABLE IF EXISTS cabinet;

CREATE TABLE cabinet (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  cabinet TEXT NOTNULL,
  temperature REAL(3) NOT NULL,
  humidity REAL(3) NOT NULL,
  created_at TEXT DEFAULT CURRENT_TIMESTAMP
);


